/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 进程存活检查 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Success"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 数据库就绪检查 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Success"];
                503: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus 文本指标 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 指标文本 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ranks/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 最新完整板块榜单 */
        get: {
            parameters: {
                query: {
                    type: components["parameters"]["BoardType"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["RankList"];
                400: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ranks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 指定交易日和时刻的板块榜单 */
        get: {
            parameters: {
                query: {
                    type: components["parameters"]["BoardType"];
                    trade_date: components["parameters"]["TradeDate"];
                    at: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["RankList"];
                400: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ranks/daily-close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 指定交易日、指定类型的完整日终榜 */
        get: {
            parameters: {
                query: {
                    /** @description 行业和概念读取 15:00 日终快照；个股读取收盘后采集并归一到 15:00 的完整榜单。 */
                    type?: "industry" | "concept" | "stock";
                    trade_date: components["parameters"]["TradeDate"];
                    /** @description 不填时读取该交易日归档；revision_id 仅为兼容标识。 */
                    revision_id?: string;
                    q?: string;
                    sort?: "rank" | "name" | "code" | "dark_money" | "main_money_inflow" | "change_pct" | "dark_activity" | "open_price" | "high_price" | "low_price" | "close_price" | "previous_close" | "volume" | "turnover" | "turnover_rate" | "amplitude";
                    direction?: "asc" | "desc";
                    page?: number;
                    page_size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["RankList"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boards/{type}/{code}/intraday": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 板块当日分钟序列，盘后回退到含 15:00 的 48 个五分钟资金点 */
        get: {
            parameters: {
                query: {
                    trade_date: components["parameters"]["TradeDate"];
                };
                header?: never;
                path: {
                    type: components["parameters"]["BoardTypePath"];
                    code: components["parameters"]["Code"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["RankList"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boards/{type}/{code}/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 板块历史五分钟资金研究序列
         * @description 盘后从 darktradetick 重新抓取，仅包含暗盘资金、明盘资金和主力净流入三项累计资金字段。
         */
        get: {
            parameters: {
                query: {
                    from: components["parameters"]["From"];
                    to: components["parameters"]["To"];
                    /** @description 指定后按该归档标识对应的交易日返回完整 48 点。 */
                    revision_id?: string;
                    interval?: "5m";
                };
                header?: never;
                path: {
                    type: components["parameters"]["BoardTypePath"];
                    code: components["parameters"]["Code"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["RankList"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boards/{type}/{code}/stocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 按截面日查询板块成分股 */
        get: {
            parameters: {
                query?: {
                    /** @description 截面日期；省略时使用服务当前的 Asia/Shanghai 日期 */
                    as_of?: components["parameters"]["AsOf"];
                };
                header?: never;
                path: {
                    type: components["parameters"]["BoardTypePath"];
                    code: components["parameters"]["Code"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["RelationList"];
                400: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/boards/{type}/{code}/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 按截面日查询板块成分股及最新行情快照
         * @description 成分关系按 as_of 还原；行情来自后台缓存快照，HTTP 请求不会同步等待东方财富。首次缓存预热返回归档数据并标记 quote_status=warming。活跃度口径为 abs(暗盘资金) / 成交额。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 截面日期；省略时使用服务当前的 Asia/Shanghai 日期 */
                    as_of?: components["parameters"]["AsOf"];
                };
                header?: never;
                path: {
                    type: components["parameters"]["BoardTypePath"];
                    code: components["parameters"]["Code"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["BoardQuoteList"];
                400: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{code}/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 按截面日查询股票所属行业和概念 */
        get: {
            parameters: {
                query?: {
                    /** @description 截面日期；省略时使用服务当前的 Asia/Shanghai 日期 */
                    as_of?: components["parameters"]["AsOf"];
                };
                header?: never;
                path: {
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["RelationList"];
                400: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{code}/research-5m": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询个股单日五分钟资金与未复权行情联合序列 */
        get: {
            parameters: {
                query: {
                    trade_date: components["parameters"]["TradeDate"];
                    /** @description 不填时读取当前个股五分钟联合数据。 */
                    revision_id?: string;
                };
                header?: never;
                path: {
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 48 个五分钟资金点及对应行情 K */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["StockResearchPoint"][];
                            meta?: Record<string, never>;
                        };
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/relations/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询指定交易日检测到的归属新增和删除事件 */
        get: {
            parameters: {
                query: {
                    trade_date: components["parameters"]["TradeDate"];
                    type?: "industry" | "concept";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 当日关系变化；首次全量基线不重复展开为 added 事件 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["StockBoardRelationChange"][];
                            meta?: Record<string, never>;
                        };
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 导出单板块 5 分钟研究 CSV */
        get: {
            parameters: {
                query: {
                    type: components["parameters"]["BoardType"];
                    code: string;
                    from: components["parameters"]["From"];
                    to: components["parameters"]["To"];
                    format?: "csv";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description UTF-8 BOM CSV */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/daily-close/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 联合导出指定交易日的行业、概念、个股三类日终榜 */
        get: {
            parameters: {
                query: {
                    trade_date: components["parameters"]["TradeDate"];
                    /** @description 不填时导出该交易日归档。 */
                    revision_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description UTF-8 BOM CSV；snapshot_kind 固定为 daily_close，snapshot_at 统一为 15:00 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 每日数据质量摘要 */
        get: {
            parameters: {
                query: {
                    trade_date: components["parameters"]["TradeDate"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 质量摘要 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QualityEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询指定交易日的归档完整性摘要 */
        get: {
            parameters: {
                query: {
                    trade_date: components["parameters"]["TradeDate"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 归档标识、内容摘要和当前指针；同一交易日通常只有一条记录 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ArchiveRevision"][];
                            meta?: Record<string, never>;
                        };
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询指定交易日的日级分析特征 */
        get: {
            parameters: {
                query: {
                    trade_date: components["parameters"]["TradeDate"];
                    revision_id?: string;
                    type?: "industry" | "concept" | "stock";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 交易日日级特征和特征集元数据 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["DailyFeature"][];
                            meta?: Record<string, never>;
                        };
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询指定交易日可用的未来收益标签 */
        get: {
            parameters: {
                query: {
                    trade_date: components["parameters"]["TradeDate"];
                    revision_id?: string;
                    /** @description 兼容旧调用；目标数据按交易日主归档读取。 */
                    target_revision_id?: string;
                    type?: "industry" | "concept" | "stock";
                    horizon?: 1 | 3 | 5 | 10 | 20;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 未来收益、相对行业收益、最大有利/不利波动标签 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["FutureReturnLabel"][];
                            meta?: Record<string, never>;
                        };
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trading-days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询交易日列表 */
        get: {
            parameters: {
                query: {
                    from: components["parameters"]["From"];
                    to: components["parameters"]["To"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 日期列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: string[];
                            meta?: Record<string, never>;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collection-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 采集运行记录 */
        get: {
            parameters: {
                query: {
                    trade_date: components["parameters"]["TradeDate"];
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 运行记录 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["CollectionRun"][];
                            meta?: Record<string, never>;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/focus/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 按动态条件筛选连续完整日终截面
         * @description 每个所选交易日都必须符合规则；资金字段单位为元，百分比行情字段使用原始小数，control_coefficient 使用百分数。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FocusScanRequest"];
                };
            };
            responses: {
                /** @description 筛选结果；完整交易日不足时 ready=false */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["FocusResult"];
                        };
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/focus/three-day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 使用内置三日策略模板筛选 */
        get: {
            parameters: {
                query?: {
                    /** @description 截面日期；省略时使用服务当前的 Asia/Shanghai 日期 */
                    as_of?: components["parameters"]["AsOf"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 与动态接口相同的筛选结果 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["FocusResult"];
                        };
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 系统和市场状态 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 状态 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["SystemStatus"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FocusCondition: {
            /** @enum {string} */
            field: "turnover" | "turnover_rate" | "change_pct" | "control_coefficient" | "dark_money" | "regular_money" | "main_money_inflow" | "dark_activity" | "dark_inflow_ratio" | "rank" | "close_price" | "amplitude" | "volume" | "up_count" | "flat_count" | "down_count";
            /** @enum {string} */
            operator: "gt" | "gte" | "lt" | "lte" | "eq" | "between";
            value: number;
            /** @description operator=between 时必填且不得小于 value */
            max_value?: number;
        };
        FocusScanRequest: {
            /** Format: date */
            as_of: string;
            consecutive_days: number;
            /** @enum {string} */
            concept_match: "all" | "any";
            concept_conditions: components["schemas"]["FocusCondition"][];
            /** @enum {string} */
            stock_match: "all" | "any";
            stock_conditions: components["schemas"]["FocusCondition"][];
            stock_scope: {
                main_board_only: boolean;
                exclude_st: boolean;
                require_qualified_concepts: boolean;
            };
        };
        FocusResult: {
            /** Format: date */
            requested_as_of?: string;
            /** Format: date */
            as_of?: string;
            ready?: boolean;
            trade_dates?: string[];
            required_days?: number;
            request?: components["schemas"]["FocusScanRequest"];
            concepts?: Record<string, never>[];
            concepts_truncated?: boolean;
            stocks?: Record<string, never>[];
            stocks_truncated?: boolean;
            rejections?: {
                /** @enum {string} */
                kind?: "concept" | "stock";
                code?: string;
                name?: string;
                /** @enum {string} */
                reason?: "condition_failed" | "non_main_board" | "st_excluded" | "missing_daily_close";
                /** Format: date */
                failed_date?: string;
                evaluation?: Record<string, never>;
            }[];
            rejections_truncated?: boolean;
            stats?: Record<string, never>;
        };
        RankRecord: {
            /** Format: date */
            trade_date: string;
            /** Format: date-time */
            snapshot_at: string;
            /** @enum {string} */
            rank_type: "stock" | "industry" | "concept";
            /** Format: int64 */
            rank: number;
            /** Format: int64 */
            market?: number;
            code: string;
            name: string;
            quote_time?: string;
            /** Format: int64 */
            latest_price_raw?: number;
            open_price?: number;
            high_price?: number;
            low_price?: number;
            close_price?: number;
            /** @description 前收盘价，用于涨跌停判断和复权日识别 */
            previous_close?: number;
            change_value?: number;
            /** @description 原始小数，展示时乘 100 */
            change_pct?: number;
            /** Format: int64 */
            volume?: number;
            /**
             * Format: int64
             * @description 成交额，单位元
             */
            turnover?: number;
            /** @description 原始小数，展示时乘 100 */
            turnover_rate?: number;
            /** @description 原始小数，展示时乘 100 */
            amplitude?: number;
            quote_available?: boolean;
            /** @description 暗盘、明盘及主力净流入字段是否来自有效上游数据 */
            money_available?: boolean;
            /** Format: int64 */
            dark_money: number;
            /** Format: int64 */
            regular_money: number;
            /** Format: int64 */
            main_money_inflow: number;
            /** @description 原始小数，展示时乘 100 */
            dark_activity?: number;
            /** @description 原始小数，展示时乘 100 */
            dark_inflow_ratio?: number;
            /** Format: int64 */
            up_count?: number;
            /** Format: int64 */
            flat_count?: number;
            /** Format: int64 */
            down_count?: number;
            leader_name?: string;
            leader_code?: string;
            /** Format: date-time */
            fetched_at?: string;
        };
        StockBoardRelation: {
            stock_code: string;
            /** Format: int64 */
            stock_market?: number;
            stock_name: string;
            board_code: string;
            board_name: string;
            /** @enum {string} */
            board_type: "industry" | "concept";
            source_order?: number;
            /** @constant */
            relation_source: "quote_clist";
            /** @constant */
            relation_scope: "all_industry_concept";
            /** Format: date */
            effective_date: string;
            /** Format: date-time */
            detected_at?: string;
            /** @description 上游成分股原始行 JSON */
            raw_data?: string;
        };
        StockBoardRelationChange: components["schemas"]["StockBoardRelation"] & {
            /** @enum {string} */
            change_type: "added" | "removed";
            run_id: string;
        };
        BoardStockQuote: components["schemas"]["StockBoardRelation"] & {
            latest_price: number;
            open_price: number;
            high_price: number;
            low_price: number;
            previous_close: number;
            /** @description 原始小数，展示时乘 100 */
            change_pct: number;
            change_value: number;
            /** Format: int64 */
            volume: number;
            /** Format: int64 */
            turnover: number;
            /** @description 原始小数，展示时乘 100 */
            turnover_rate: number;
            /** @description 原始小数，展示时乘 100 */
            amplitude: number;
            quote_time: string;
            /** Format: date-time */
            fetched_at?: string;
            quote_available: boolean;
            /**
             * Format: int64
             * @description 同日个股暗盘榜排名
             */
            dark_rank: number;
            /** Format: int64 */
            dark_money: number;
            /** Format: int64 */
            main_money_inflow: number;
            /** @description 个股暗盘榜原始活跃度，口径为 abs(暗盘资金) / 成交额 */
            dark_activity: number;
            dark_data_available: boolean;
        };
        CollectionRun: {
            run_id?: string;
            /** Format: date-time */
            snapshot_at?: string;
            /** @enum {string} */
            snapshot_kind?: "minute_work" | "research_5m" | "daily_close" | "stock_kline_5m";
            /** @enum {string} */
            rank_type?: "stock" | "industry" | "concept";
            /** @enum {string} */
            status?: "running" | "success" | "partial" | "failed" | "skipped";
            /** Format: date */
            requested_date?: string;
            actual_trade_date?: string;
            expected_total?: number;
            fetched_total?: number;
            page_count?: number;
            attempt_count?: number;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            finished_at?: string;
            /** Format: int64 */
            duration_ms?: number;
            error_code?: string;
            error_message?: string;
        };
        SystemStatus: {
            /** Format: date-time */
            server_time?: string;
            /** @constant */
            timezone?: "Asia/Shanghai";
            /** @enum {string} */
            market_status?: "pre_open" | "open" | "lunch_break" | "closed";
            trading_day?: boolean;
            /** Format: date */
            latest_trading_day?: string;
            /** Format: int64 */
            uptime_seconds?: number;
            trading_calendar?: {
                /** Format: date */
                valid_through?: string;
                /** Format: date-time */
                updated_at?: string;
                source?: string;
                days_remaining?: number;
                expired?: boolean;
            };
        };
        StockResearchPoint: {
            /** Format: date */
            trade_date?: string;
            /** Format: date-time */
            snapshot_at?: string;
            /** Format: int64 */
            market?: number;
            code?: string;
            /** Format: int64 */
            money_rank?: number;
            /** Format: int64 */
            dark_money?: number;
            /** Format: int64 */
            regular_money?: number;
            /** Format: int64 */
            main_money_inflow?: number;
            open_price?: number;
            high_price?: number;
            low_price?: number;
            close_price?: number;
            /** Format: int64 */
            volume?: number;
            /** Format: int64 */
            turnover?: number;
            amplitude?: number;
            change_pct?: number;
            change_value?: number;
            turnover_rate?: number;
            money_available?: boolean;
            kline_available?: boolean;
        };
        ArchiveRevision: {
            revision_id?: string;
            /** Format: date */
            trade_date?: string;
            revision_no?: number;
            previous_revision?: string;
            content_sha256?: string;
            /** Format: date-time */
            created_at?: string;
        };
        DailyFeature: {
            revision_id?: string;
            /** Format: date */
            trade_date?: string;
            /** @enum {string} */
            rank_type?: "industry" | "concept" | "stock";
            /** Format: int64 */
            market?: number;
            code?: string;
            name?: string;
            primary_industry_code?: string;
            signed_dark_activity?: number;
            capital_intensity?: number;
            control_coefficient?: number;
            rank_percentile?: number;
            turnover_percentile?: number;
            dark_money_percentile?: number;
            self_turnover_percentile_5?: number | null;
            self_turnover_percentile_10?: number | null;
            self_turnover_percentile_20?: number | null;
            self_turnover_percentile_60?: number | null;
            self_dark_money_percentile_5?: number | null;
            self_dark_money_percentile_10?: number | null;
            self_dark_money_percentile_20?: number | null;
            self_dark_money_percentile_60?: number | null;
            /** Format: int64 */
            rank_change_1?: number;
            consecutive_inflow_days?: number;
            /** Format: int64 */
            money_acceleration?: number;
            curve_available?: boolean;
            morning_dark_share?: number;
            afternoon_dark_share?: number;
            late_dark_share?: number;
            max_inflow_minute_index?: number;
            max_outflow_minute_index?: number;
            /** Format: int64 */
            tail_acceleration?: number;
            /** Format: int64 */
            max_dark_drawdown?: number;
            intraday_reversal?: boolean;
            price_money_divergence?: boolean;
        };
        FutureReturnLabel: {
            signal_revision_id?: string;
            target_revision_id?: string;
            /** Format: date */
            signal_date?: string;
            /** Format: date */
            target_date?: string;
            /** @enum {integer} */
            horizon?: 1 | 3 | 5 | 10 | 20;
            /** @enum {string} */
            rank_type?: "industry" | "concept" | "stock";
            /** Format: int64 */
            market?: number;
            code?: string;
            return_rate?: number;
            relative_industry_return?: number | null;
            max_favorable_return?: number;
            max_adverse_return?: number;
            label_version?: string;
            /** Format: date-time */
            generated_at?: string;
        };
        QualityEnvelope: {
            data?: {
                /** Format: date */
                trade_date?: string;
                /** @enum {string} */
                rank_type?: "industry" | "concept";
                expected_minutes?: number;
                collected_minutes?: number;
                expected_research_snapshots?: number;
                collected_research_snapshots?: number;
                expected_daily_close_snapshots?: number;
                collected_daily_close_snapshots?: number;
                missing_minutes?: string[];
                missing_research_snapshots?: string[];
                missing_daily_close_snapshots?: string[];
            }[];
            meta?: {
                /** Format: date */
                trade_date?: string;
                stock_archive?: {
                    /** Format: date */
                    trade_date?: string;
                    expected_stocks?: number;
                    /** @constant */
                    expected_points?: 48;
                    expected_kline_stocks?: number;
                    money_rows?: number;
                    kline_rows?: number;
                    daily_close_rows?: number;
                    daily_kline_rows?: number;
                    /** Format: date-time */
                    money_archived_at?: string;
                    /** Format: date-time */
                    kline_archived_at?: string;
                };
                archive_manifest?: {
                    /** Format: date */
                    trade_date?: string;
                    /** @enum {string} */
                    status?: "incomplete" | "complete";
                    industry_close_rows?: number;
                    industry_money_rows?: number;
                    concept_close_rows?: number;
                    concept_money_rows?: number;
                    stock_close_rows?: number;
                    stock_money_rows?: number;
                    stock_kline_rows?: number;
                    stock_daily_kline_rows?: number;
                    expected_stock_rows?: number;
                    expected_stock_kline_rows?: number;
                    code_count?: number;
                    code_set_sha256?: string;
                    kline_source_counts?: {
                        [key: string]: number;
                    };
                    darktrade_contract?: string;
                    darktradetick_contract?: string;
                    stock_kline_contract?: string;
                    parser_version?: string;
                    validation_errors?: string[];
                    /** Format: date-time */
                    completed_at?: string;
                    /** Format: date-time */
                    updated_at?: string;
                    current_revision_id?: string;
                    revision_no?: number;
                };
            };
        };
        ErrorEnvelope: {
            error?: {
                code: string;
                message: string;
            };
        };
    };
    responses: {
        /** @description 成功 */
        Success: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": Record<string, never>;
            };
        };
        /** @description 错误 */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 榜单或序列 */
        RankList: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    data?: components["schemas"]["RankRecord"][];
                    meta?: Record<string, never>;
                };
            };
        };
        /** @description 按“最近基线 + 截面日前累计变更”还原的关系列表 */
        RelationList: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    data?: components["schemas"]["StockBoardRelation"][];
                    meta?: Record<string, never>;
                };
            };
        };
        /** @description 成分关系与最新行情快照；行情不可用时仍返回成分关系 */
        BoardQuoteList: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    data?: components["schemas"]["BoardStockQuote"][];
                    meta?: {
                        /** @enum {string} */
                        quote_status?: "ready" | "warming" | "stale" | "unavailable";
                        stale?: boolean;
                        cache_age_ms?: number;
                        quote_source?: string;
                        quote_available?: boolean;
                        quote_error?: string;
                    };
                };
            };
        };
    };
    parameters: {
        BoardType: "industry" | "concept";
        BoardTypePath: "industry" | "concept";
        Code: string;
        TradeDate: string;
        /** @description 截面日期；省略时使用服务当前的 Asia/Shanghai 日期 */
        AsOf: string;
        From: string;
        To: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
